name: flutter_application_1
description: "Nol Persen Kafe - Artisanal Ledger"
publish_to: 'none'
version: 2.4.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.6
  flutter_dotenv: ^5.1.0
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.2
  fl_chart: ^0.68.0
  cached_network_image: ^3.3.1
  image_picker: ^1.2.1
  fancy_shimmer_image: ^2.0.3
  flutter_local_notifications: ^17.2.4
  flutter_secure_storage: ^10.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/logo_splash.png

flutter_native_splash:
  color: "#F5F5F5"
  image: assets/images/logo_splash.png
  android: true
  ios: true
  web: true
  fullscreen: true

  android_12:
    color: "#F5F5F5"
    image: assets/images/logo_splash.png
    icon_background_color: "#F5F5F5"

flutter_launcher_icons:
  android: "ic_launcher"
  image_path: "assets/app_icons/logo.png"